export function DocsPage(){
  return(<div className="fade-in"><div className="page-content"><h2>Documentation</h2><p>Welcome to LiteWill Protocol — trustless digital inheritance on LitVM LiteForge Testnet.</p><h3>What is LiteWill Protocol?</h3><p>LiteWill Protocol is a Dead Man's Switch for your digital life. Store encrypted secrets — crypto keys, property documents, company files, passwords — in a vault. Check in regularly. If you stop checking in, your designated heirs automatically inherit everything.</p><h3>How It Works</h3><p><strong>1. Create a Vault</strong> — Store encrypted secrets, assign heirs with percentage splits, set a trusted co-signer.</p><p><strong>2. Check In Regularly</strong> — Prove you are alive every 7, 14, or 30 days.</p><p><strong>3. If You Go Dark</strong> — When your deadline passes, anyone can mark the vault claimable. Heirs and co-signer are notified automatically.</p><p><strong>4. Claim & Inherit</strong> — Heir initiates claim, co-signer approves, 3-day timelock, then release.</p><h3>Co-Signer Waiver</h3><p>If the co-signer does not respond within your chosen waiver period, their approval is automatically waived and the heir can release alone.</p><h3>Secret Verification Question</h3><p>Set a secret question only your family knows. Heirs must answer correctly before claiming. The answer is encrypted and stored securely.</p><h3>Adding LitVM to MetaMask</h3><p>Network: LiteForge Testnet · RPC: https://liteforge.rpc.caldera.xyz/http · Chain ID: 4441 · Currency: zkLTC · Explorer: testnet.litvm.com</p><h3>Support</h3><p>Email: liteprotocol@gmail.com</p></div></div>);
}

export function PrivacyPage(){
  return(<div className="fade-in"><div className="page-content"><h2>Privacy Policy</h2><p style={{color:"var(--text-muted)",fontSize:12}}>Last Updated: June 2026</p><h3>1. Data Collection</h3><p>LiteWill Protocol is a decentralized application. We do not collect, store, or process personal data on centralized servers. All vault data is stored on the public LitVM blockchain and encrypted IPFS nodes.</p><h3>2. Encryption</h3><p>All secrets are encrypted in your browser using Lit Protocol before upload. Raw content is never transmitted. Only designated heirs can decrypt it.</p><h3>3. Blockchain Transparency</h3><p>Wallet addresses, vault creation timestamps, check-in activity, and claim events are publicly visible on-chain. Encrypted secret data is stored only as an encrypted hash.</p><h3>4. Contact Information</h3><p>Email and phone numbers for heirs and co-signers are stored locally in your browser. They are used only to send inheritance notifications and never stored on any server.</p><h3>5. Third-Party Services</h3><p>We use Caldera RPC endpoints for LitVM access and Lit Protocol for encryption. Their privacy policies govern their data handling.</p><h3>6. Cookies</h3><p>LiteWill Protocol does not use cookies or analytics trackers. Theme and profile data are stored locally in your browser only.</p><h3>Contact</h3><p>liteprotocol@gmail.com</p></div></div>);
}

export function TermsPage(){
  return(<div className="fade-in"><div className="page-content"><h2>Terms of Service</h2><p style={{color:"var(--text-muted)",fontSize:12}}>Last Updated: June 2026</p><h3>1. Acceptance</h3><p>By using LiteWill Protocol, you agree to these terms. The protocol is provided "as is" without warranty.</p><h3>2. Smart Contract Risks</h3><p>Smart contracts involve inherent risks including bugs and potential loss of funds. You use the protocol at your own risk.</p><h3>3. Testnet Notice</h3><p>Currently deployed on LitVM LiteForge Testnet. Testnet assets have no real monetary value. Do not store sensitive data on testnet.</p><h3>4. User Responsibilities</h3><p>You are responsible for safeguarding your wallet and private keys. We cannot recover lost funds or reverse blockchain transactions.</p><h3>5. Notifications</h3><p>Email and push notifications are best-effort. The smart contract functions as designed regardless of notification delivery.</p><h3>6. No Legal Advice</h3><p>LiteWill Protocol is a technology tool, not a legal service. It does not replace a legally valid will. Consult a qualified attorney for formal estate planning.</p><h3>Contact</h3><p>liteprotocol@gmail.com</p></div></div>);
}

export function SupportPage(){
  return(<div className="fade-in"><div className="page-content"><h2>Support</h2><p>Need help with LiteWill Protocol? We're here to assist you.</p><h3>Email Support</h3><p>Send your question to:</p><div style={{background:"var(--accent-subtle)",border:"1px solid var(--border-accent)",padding:"16px 20px",marginBottom:20,fontFamily:"'Share Tech Mono',monospace",fontSize:14,color:"var(--accent-text)"}}>liteprotocol@gmail.com</div><h3>Common Issues</h3><p><strong>MetaMask not connecting</strong> — Make sure you are on LiteForge Testnet (Chain ID 4441).</p><p><strong>Not enough zkLTC</strong> — Visit hub.caldera.xyz and claim free testnet tokens.</p><p><strong>Transaction failing</strong> — Ensure you have zkLTC for gas fees.</p><p><strong>Vault not showing</strong> — Connect the same wallet address that created the vault.</p><h3>GitHub</h3><a href="https://github.com/PRIMEHOMEBOY/Lite-Will-Protocol" target="_blank" rel="noopener noreferrer" style={{display:"inline-block",background:"var(--accent)",color:"#fff",padding:"10px 20px",fontFamily:"'Share Tech Mono',monospace",fontSize:11,letterSpacing:".15em",textTransform:"uppercase",textDecoration:"none",marginBottom:16}}>Open a GitHub Issue</a><h3>Follow Us on X</h3><a href="https://x.com/lite_will_pro" target="_blank" rel="noopener noreferrer" style={{display:"inline-block",background:"#000",color:"#fff",padding:"10px 20px",fontFamily:"'Share Tech Mono',monospace",fontSize:11,letterSpacing:".15em",textTransform:"uppercase",textDecoration:"none"}}>@lite_will_pro</a></div></div>);
}
